### ISSUE TITLE
Improve performance of findMatchingRequest()

### ISSUE THREAD

**Issue by Berdir** [md-systems/redirect#19]
I've been doing some profiling, and the request subscriber uses ~3.5% of the whole request time (which is 300-500ms).

2% of the total time is that method. And it's doing a loadByProperties(), which is doing an entity query, which needs to load the field storage definitions, and so on, and so on.

![flamegraph](https://cloud.githubusercontent.com/assets/40826/7156119/6073bb60-e364-11e4-8bd5-3d4edf626c82.png)

**Comment by Berdir** [comment]
Note: The actual numbers inside aren't too reliable, I just did two 200 samples, and the width of those "towers" is exactly one sample of those. But the whole time should be somewhat reliable

**Comment by Berdir** [comment]
Here's a better flamegraph that has more samples. Similar picture.

![flamegraph2](https://cloud.githubusercontent.com/assets/40826/7158777/95e3fefe-e37d-11e4-835e-a941925a9821.png)

**Comment by jhedstrom** [comment]
I'll take a look into this.
