### ISSUE TITLE
redirect_page_cache_clear() missing

### ISSUE THREAD

**Issue by patkai** [md-systems/redirect#29]
I'm wondering how the D7 function redirect_page_cache_clear() works for others. (It's in src/Form/RedirectSettingsForm.php, line 105):

```
public function submitForm(array &$form, FormStateInterface $form_state) {
  $config = $this->config('redirect.settings');
  foreach ($form_state->getValues() as $key => $value) {
    if (strpos($key, 'redirect_') !== FALSE) {
      $config->set(str_replace('redirect_', '', $key), $value);
    }
  }
  $config->save();
  redirect_page_cache_clear();
  drupal_set_message(t('Configuration was saved.'));
}
```

For me it breaks the settings form submit, should we remove it? Also, should we just remove it or replace it with an alternative?

**Comment by Berdir** [comment]
This should be removed, yes. 

We can either clear the rendered cache tag or we can add the cache tag for the config to the redirect response, just like we add the cache tags for the $redirect entity already. That would however only affect redirects that are already cached and not pages that would then allow redirects and didn't before.

**Comment by Berdir** [comment]
This has been dealt with as part of the globalredirect merge.
