### ISSUE TITLE
Redirects are no longer storing internal paths

### ISSUE THREAD

**Issue by jhedstrom** [md-systems/redirect#5]
Once #4 is merged, the remaining tests that aren't passing are due to redirects storing alias information instead of internal path (for instance, one failing test is looking for a redirect to `node/1`). Since the `Url::getInternalPath()` method is deprecated, this module may need to store router info when available.

**Comment by Berdir** [comment]
Yeah, we need to refactor quite a bit there, but I'm currently waiting out the whole url discussions that are going on in Core. Link fields might also still change quite heavily.

**Comment by Berdir** [comment]
Some of the related issues:

https://www.drupal.org/node/2360027
https://www.drupal.org/node/2407505

**Comment by Berdir** [comment]
I think this has been addressed by https://github.com/md-systems/redirect/pull/6
