### ISSUE TITLE
Apply button doesn't add redirect in Drupal 8.0.0-beta15

### ISSUE THREAD

**Issue by nhero** [md-systems/redirect#56]
I have a fresh Drupal 8 beta 15 install and am trying to add a redirect, however, when clicking the apply button nothing gets saved to the database and no error is generated.

**Comment by phenaproxima** [comment]
I don't get it -- the Apply button (I assume you're talking about the one at /admin/config/search/redirect) sets the search filters; as far as I know, it shouldn't save anything into the database.

**Comment by zengenuity** [comment]
I can see where somebody might make this mistake because the button is labeled "Apply". It's "Filter" in the D7 version. But, otherwise, this is not a bug.

**Comment by Berdir** [comment]
Apply is the views default I think and AFAIK used elsewhere too. But yes, that sounds like that was the problem then.
