### ISSUE TITLE
Redirect fails if dblog module is not enabled.

### ISSUE THREAD

**Issue by paul-mckibben** [md-systems/redirect#58]
It is generally a best practice to disable dblog on production sites to improve performance. However, if you disable dblog, you cannot configure redirects. If you go to /admin/config/search/redirect, the following error appears in the Apache error log:

`Uncaught PHP Exception Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: "Route "redirect.fix_404" does not exist." at /docroot/core/lib/Drupal/Core/Routing/RouteProvider.php line 176`

Instead of having the route for redirect.fix_404 depend on the optional dblog module, I suggest having the controller check whether dblog is enabled, and provide a helpful message if it is not.

**Comment by Berdir** [comment]
Merged the PR
