### ISSUE TITLE
WSOD on Redirect admin page after adding redirect

### ISSUE THREAD

**Issue by tannerjfco** [md-systems/redirect#61]
After creating a redirect, I get a WSOD returning to the main redirect admin UI at `/admin/config/search/redirect` It seems the redirect is saved and works, as I am redirected as expected with the test entries made. Hitting that admin page, I get the following error on my system php error log:

PHP Fatal error:  Declaration of Drupal\redirect\Plugin\Field\FieldFormatter\RedirectSourceFormatter::viewElements() must be compatible with Drupal\Core\Field\FormatterInterface::viewElements(Drupal\Core\Field\FieldItemListInterface $items) in modules/redirect/src/Plugin/Field/FieldFormatter/RedirectSourceFormatter.php on line 25

**Comment by Berdir** [comment]
That's because the latest redirect version has been updated to work with Drupal 8.0.0-dev. You need to use an older commit if you want to use redirect with beta15.
