### ISSUE TITLE
Error after adding first redirect when accessing redirect config page after submit.

### ISSUE THREAD

**Issue by sk33lz** [md-systems/redirect#62]
I'm using the Drupal core git repo at revision 1d1fe19702f5dc6894acc45431b1d0c85ab306d7 with the latest commit here, f15c76f4ed96b52217eb8cc2f80dce22cdf3673e. I was able to add a redirect, and the redirect actually works if I visit the URL, but the config page is no longer accessible after adding the first entry. This issue is repeatable.

I receive the following error:

```
Fatal error: Declaration of Drupal\redirect\Plugin\Field\FieldFormatter\RedirectSourceFormatter::viewElements() must be compatible with Drupal\Core\Field\FormatterInterface::viewElements(Drupal\Core\Field\FieldItemListInterface $items) in /var/www/sitename/code/modules/contrib/redirect/src/Plugin/Field/FieldFormatter/RedirectSourceFormatter.php on line 25
```

**Comment by phenaproxima** [comment]
I cannot reproduce this with revision 07662e of Drupal 8 and revision f15c76 of Redirect.

**Comment by sk33lz** [comment]
I'm currently testing with revision ff622b of core and revision dcea7fb715a2fe8a584686109a622bed6b24c77c of redirect here and I can no longer reproduce this error. Closing.
