### ISSUE TITLE
input placeholder error in add redirect

### ISSUE THREAD

**Issue by edurenye** [md-systems/redirect#67]
When you try to add a redirect in the form if you start filing the path, the when you try to fill the rest of fields after the validation of path the input placeholder is moved again to the path.
So it don't let you fill the rest of fields.

**Comment by podarok** [comment]
The only way to approach adding redirect right now is to load a page without JS and it works

**Comment by juampynr** [comment]
This was fixed at https://github.com/md-systems/redirect/pull/81.
