### ISSUE TITLE
RedirectTerminateSubscriber::onKernelTerminateLogRedirect() invalidates cache tags and entity storage every time a redirect is usd

### ISSUE THREAD

**Issue by Berdir** [md-systems/redirect#7]
I'm not sure yet where this information should be stored, but doing it through entity->save() is bad for multiple reasons:
- A save invalidates the storage cache
- It also invalidates the redirect:$id and redirect_list cache tags, which aren't actually used, which results in two additional sql queries (updating the checksum table), and possibly notification of external caching system which also means that a cache redirect would be invalidated again immediately after caching it, every time.

Two ways to fix this:
1. add a new method on the storage handler specifically for this, which would at least avoid the cache tags, but we still have to invalidate the storage cache to get updated results in e.g. views (query would work, though)
2. Store it somewhere else, but it still needs to be possible to query it.

**Comment by jhedstrom** [comment]
While we're at it, should this behavior be configurable? Any site behind Varnish etc would not have accurate counts from this data anyway...

**Comment by Berdir** [comment]
Possibly, yes.

The purge function actually checks the page cache setting (which will possibly go away soon) and doesn't invalidate, ever, anyway. And there's a setting after what time redirects should be removed. Maybe a new setting that also allows to disable this completely and that would then also disable purging?

Happy to accept pull requests for that if you have time, would actually prefer to disable it for my site as well.

**Comment by Berdir** [comment]
Maybe also re-think/fix the caching relation options, there's quite some not-working/commented out code, like a check for a non-existing invoke_hooks setting on the purge options.

8.x actually caches responses by default, didn't check yet, but it likely just works for redirects unless we explicitly disable it. And using cache tags, we can also make invalidation of it work.

**Comment by Berdir** [comment]
This was fixed by https://github.com/md-systems/redirect/issues/10
