### ISSUE TITLE
Fields instances are not stored as redirect entities upon save.

### ISSUE THREAD

**Issue by Jaesin** [md-systems/redirect#75]
When the redirect check happens in `Drupal\redirect\RedirectRepository` redirects entered as redirect fields in nodes are not searched. 

That makes since because loading field config and field instances on a request event would be terrible for performance. I would expect that field type redirects are discovered via state or cache but also could also be duplicated as redirect entities.

Am I missing something or is there more work to be done with redirect fields?

**Comment by Berdir** [comment]
The redirect field is just used internally for the redirect entity itself. It's not meant to be added to nodes, that's not how it works. See https://github.com/md-systems/redirect/issues/69.

**Comment by Berdir** [comment]
I've now added the no_ui flag to that field type, it won't show up in the UI anymore.

**Comment by Jaesin** [comment]
OK, so no UI for redirects on the entity edit form yet?
Is there a plan for it?
