### ISSUE TITLE
Redirect Source Widget ajax validation fails

### ISSUE THREAD

**Issue by lauriii** [md-systems/redirect#79]
Redirect source widget ajax validation causes a warning and recoverable fatal error which prevents me from creating redirects:

`Warning: array_merge_recursive(): Argument #1 is not an array in Drupal\Core\Render\BubbleableMetadata::mergeAttachments() (line 170 of core/lib/Drupal/Core/Render/BubbleableMetadata.php).`

`Recoverable fatal error: Argument 1 passed to Drupal\Core\Ajax\AjaxResponse::setAttachments() must be of the type array, null given, called in core/lib/Drupal/Core/Ajax/AjaxResponse.php on line 57 and defined in Drupal\Core\Ajax\AjaxResponse->setAttachments() (line 42 of core/lib/Drupal/Core/Render/AttachmentsTrait.php).`

**Comment by juampynr** [comment]
Created https://github.com/md-systems/redirect/pull/81
