### ISSUE TITLE
Mirror to Drupal.org

### ISSUE THREAD

**Issue by rainer-friederich** [md-systems/redirect#92]
I don't know whats the roadmap for this module, but the base is usable.
Would you mind to mirror the 8.x branch to Drupal.org and implement SemVer? 

That would allow us to use drupal-pakagist for our composer setup properly.

**Comment by Berdir** [comment]
That's not up to me, I don't have access to do that. davereid promised to look at redirect once pathauto stabilizes (beta?). 

Note that you can use composer, you just have to specify it as a repository and use dev-8.x-1.x as the version.

**Comment by rainer-friederich** [comment]
Okay thank you, i tried 8.x-1.x as Branch but that didn't work.

**Comment by Berdir** [comment]
See https://github.com/md-systems/redirect/pull/57 for more infos on that.
